#!/bin/sh

# file managing
alias cp='cp -v'
alias mv='mv -v'
alias rm='rm -v'

alias htop='htop --tree'

alias find-node-modules='find . -name 'node_modules' -prune'
alias ls='ls --color=auto'
alias du='du -sh'
alias diff='diff --color=auto'
alias todo='nvim ~/.local/share/todo'
alias vim='nvim'
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME'
alias paccache-last2='paccache -rk2'
alias waybar-refresh='killall waybar ; waybar & disown'
