#!/bin/sh
# file managing
alias cp='cp -v'
alias mv='mv -v'
alias rm='rm -v'

alias ls='ls --color=auto'
alias diff='diff --color=auto'
alias todo='nvim ~/.local/share/todo'
alias vim='nvim'
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME'
alias paccache-last2='paccache -rk2'
