#!/bin/zsh

# export QT_QPA_PLATFORM=wayland
# export ZDOTDIR="$HOME/.config/zsh"
# export GPG_TTY=$(tty)

# Path
# export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export path="~/.npm-global/bin:$path"
