#!/bin/zsh

# XDG Settings
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_SCREENSHOTS_DIR="$HOME/pictures/screenshots"
export XDG_STATE_HOME="$HOME/.local/state"

# Programs
export EDITOR=nvim
export TERMINAL=alacritty
export BROWSER=chromium

# Settings
export QT_QPA_PLATFORM=wayland
export FZF_DEFAULT_OPS='--layout=reverse -i'
export TERM=xterm-256color
export ZDOTDIR="$HOME/.config/zsh"
export GPG_TTY=$(tty)
export PNPM_HOME="/home/sotiris/.local/share/pnpm"

# Path
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/bin/statusbar:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="~/.npm-global/bin:$PATH"
export PATH="$PNPM_HOME:$PATH"
